version: "3.7"

services:
  apache:
    image: openmage/php-dev:7.3-apache
    build:
      context: docker-magento/7.3/apache
    hostname: openmage.docker
    ports:
      - "80:80"
    volumes:
      - ../..:/var/www/html
    environment:
      - VIRTUAL_HOST=openmage.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - ENABLE_SENDMAIL=true
      - XDEBUG_CONFIG=remote_connect_back=1 remote_enable=1 idekey=phpstorm
    links:
      - mysql

  cron:
    image: openmage/php-dev:7.3-cli
    build:
      context: docker-magento/7.3/cli
    working_dir: /var/www/html
    command: /run-cron.sh
    volumes:
      - ../..:/var/www/html
    environment:
      - ENABLE_SENDMAIL=true
    links:
      - mysql

  cli:
    build:
      context: docker-magento/7.3/cli
    working_dir: /var/www/html
    command: /bin/true
    volumes:
      - ../..:/var/www/html
#    environment:
#      - AWS_ACCESS_KEY_ID=00000000000000000000
#      - AWS_SECRET_ACCESS_KEY=0000000000000000000000000000000000000000
#      - AWS_REGION=eu-west-1
#      - AWS_BUCKET=magedbm
#      - AWS_MEDIA_BUCKET=magemm
    links:
      - mysql
      - "apache:openmage.docker"

  mysql:
    image: mysql:5.7
    ports:
      - 3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
