# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: OpenMage Docs
site_url: https://docs.openmage.org/
repo_url: https://github.com/OpenMage/magento-lts
repo_name: OpenMage/magento-lts
edit_uri: edit/main/docs
copyright: OpenMage contributors
site_author: OpenMage contributors
site_description: >-
  Magento - Long Term Support.
docs_dir: docs/content

# Configuration
theme:
  name: material
  favicon: assets/images/favicon.ico
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  icon:
    icon:
      annotation: material/plus-circle
    tag:
      code: fontawesome/solid/code
      config: fontawesome/solid/clipboard-check
      css: fontawesome/brands/css3
      debug: fontawesome/solid/bug-slash
      documentation: fontawesome/regular/file
      events: fontawesome/regular/calendar-xmark
      html: fontawesome/brands/html5
      install: fontawesome/solid/plus
      js: fontawesome/brands/js
      modules: fontawesome/regular/square-plus
      php: fontawesome/brands/php
      security: fontawesome/solid/shield
      share: fontawesome/solid/share
      tinymce: fontawesome/solid/wand-magic-sparkles

# Plugins
plugins:
  - blog:
      archive_toc: true
      categories_toc: true
      pagination: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
  - search
  - tags:
      tags_file: tags.md
  - redirects:
      redirect_maps:
  - minify:
      minify_html: true
      cache_safe: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenMage/magento-lts
    - icon: fontawesome/brands/discord
      link: https://discord.gg/R2q5WadstX
    - icon: fontawesome/brands/stack-overflow
      link: https://magento.stackexchange.com/tags/openmage
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/OpenMageProject
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OpenMageProject
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/13655485/
    - icon: fontawesome/brands/mastodon
      link: https://phpc.social/@OpenMageProject
  generator: false
  tags:
    Configuration: config
    Contribute: share
    CSS: css
    Debug: debug
    Development: code
    Documentation: documentation
    Events: events
    HTML5: html
    Install: install
    JavaScript: js
    Modules: modules
    PHP-7.4: php
    PHP-8.0: php
    PHP-8.1: php
    PHP-8.2: php
    PHP-8.3: php
    PHP-8.4: php
    TinyMCE: tinymce
    Security: security

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: OpenMage
      repo: magento-lts
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - docs_includes/abbreviations.md
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty

nav:
  - 'Get started':
      - index.md
      - users/requirements.md
      - 'Installing':
          - users/install/index.md
          - users/install/use-composer.md
          - users/install/use-git.md
          - users/install/secure-install.md
      - 'Changelog':
          - developers/changelog/index.md
          - developers/changelog/new-config.md
          - developers/changelog/new-events.md
          - developers/changelog/soap-wsdl.md
      - 'Versioning':
          - users/versioning/index.md
          - users/versioning/maintained.md
      - 'Quick links':
          - tags.md
  - 'API':
      - 'REST':
          - api/rest/common_http_status_codes.md
          - api/rest/http_methods.md
          - api/rest/get_filters.md
          - 'Resources':
              - 'Products':
                  - api/rest/resources/products/product_categories.md
              - 'Customers':
                  - api/rest/resources/customers.md
          - api/rest/response_formats.md
          - api/rest/testing_rest_resources.md
  - 'Development':
      - 'Installation':
          - developers/tools/ddev.md
          - developers/tools/oneline.md
      - 'Coding Style':
          - developers/coding-style/per-2.0.md
      - 'Events':
          - developers/events/list.md
      - 'Tools':
          - developers/tools/n98-magerun.md
          - developers/tools/phpstorm.md
      - 'Multistore':
          - developers/error-pages.md
      - 'Samples':
          - developers/samples/php-ini.md
          - developers/samples/robots-txt.md
      - 'Guides':
          - blog/posts/guides/2023-01-09-dynamic-blocks.md
          - blog/posts/guides/2022-08-17-observer.md
          - blog/posts/guides/2023-05-01-customize-your-openmage.md
          - blog/posts/guides/2024-02-17-ddev-windows-10.md
      - 'Documentation':
          - developers/mkdocs.md
  - 'Modules':
      - users/modules/index.md
      - users/modules/analytics.md
      - users/modules/backend.md
      - users/modules/cache.md
      - users/modules/captcha.md
      - users/modules/cron.md
      - users/modules/email.md
      - users/modules/frontend.md
      - users/modules/images.md
      - users/modules/log-debug.md
      - users/modules/payment.md
      - 'Themes':
          - users/modules/themes/frontend.md
      - 'User Guides':
          - users/modules/user-guides/swatches.md
  - 'Blog':
      - blog/index.md
