name: OpenMage LTS - Unit Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: OpenMage/Testfield
          path: ./

      - name: php & Composer version
        run: php --version && composer --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Checkout OpenMage repo
        uses: actions/checkout@v2
        with:
          path: openmage

      - name: Install OpenMage dependencies
        working-directory: ./openmage
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: run phpUnit
        run: bash ./run_unit_tests.sh

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: output/*.xml
