name: Update PhpStorm Meta-Files

on:
  # Run automatically every month.
  schedule:
    - cron: '0 0 1 * *'
  workflow_call:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  update_phpstorm_meta:
    name: Update PhpStotm meta-files
    runs-on: [ubuntu-latest]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-req=ext-*

      - name: Install n98/magerun
        run: composer require --dev n98/magerun:dev-develop

      - name: Update PhpStorm Meta-Files
        run: php -f vendor/bin/n98-magerun dev:ide:phpstorm:meta

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: update phpstorm meta-files
          title: Updated PhpStorm meta-files
          body: |
            - Updated PhpStorm Meta-Files
            
            Thanks to [n98/magerun][1]
            
            [1]: https://github.com/netz98/n98-magerun
          branch: phpstorm-meta
          labels: chore
          base: main
